### ISSUE TITLE
ExtIO support seems to require Windows.h?

### ISSUE THREAD

**Issue by almule** [martinmarinov/TempestSDR#10]
I tried using the precompiled JAR in Ubuntu 17.04 x64 but I could not choose an ExtIO source (incompatible or libraries missing, before I could choose the file.) Trying the JAR with 32 bit Java gave me an error upon launch (the library was not compiled for my OS/Architecture). I tried compiling from source but the ExtIO library required Windows.h for compiling.

Also, if I am completely misinterpreting this and ExtIO is a windows-based function, how can I use the RTL-SDR with this software on linux?

Thanks so much for your help,
Alex

**Comment by martinmarinov** [comment]
Hello Alex,

There is no way at the moment to use RTL-SDRs under Linux I'm afraid. Indeed the extio plugin is a Windows only concept.

It can be done but requires developing a RTL-SDR only module.

Regards,
Martin

**Comment by mgkuhn** [comment]
Also note that the RTL-SDR, with its ~2 MHz bandwidth limit, is not a very useful front-end for video signals, where you want to have at least an order of magnitude more bandwidth.

**Comment by dennisdebel** [comment]
Ah thats a shame. It explains my confusion on the whole extio thing though
:) Affraid im not (yet) in the position to make usefull contribution to a
linux solution, but the project sure is a motivation! Keep up the good work!
