### ISSUE TITLE
Comment Algorithms

### ISSUE THREAD

**Issue by xloem** [martinmarinov/TempestSDR#14]
TempestSDR appears to include some sweet algorithms for analyzing signals to provide for van eck phreaking.  However, the details of this code are completely uncommented, making it labor intensive to learn from or expand upon it.  Please comment the purpose and method of all functions.

**Comment by martinmarinov** [comment]
The code is not something I'm particularly proud of :D It was done so it is practical rather than beautiful. Never had the time to properly clean it up.

The only parts that are interesting are:
* Decimation
* AM demodulation
* Fast autocorrelation

Those are pretty much the main DSP algorithms used and needed to get this to work. They are a bit spaghettificated in the code I'm afraid.

**Comment by mgkuhn** [comment]
[Martin's Master thesis](https://raw.githubusercontent.com/martinmarinov/TempestSDR/master/documentation/acs-dissertation.pdf) does explain parts of the the underlying theory and the algorithms used in his implementation in Chapter 3. I am in the process of writing up a more detailed tutorial on algorithms for visualizing compromising video emanations from SDR IQ data (including some newer algorithms not yet found in TempestSDR). I'll add a note here when that paper is ready.

**Comment by reyesjl** [comment]
Hey which files do you need the comments on?

**Comment by martinmarinov** [comment]
@madman-bob has created a pull request with some comments that is now merged into the main repo.

Thanks to @madman-bob for his effort and time!

**Comment by xloem** [comment]
@madman-bob, thanks for addressing as much of this as you did.  I posted the bounty to help the baseline of information security a little.

**Comment by madman-bob** [comment]
I'm glad to have been of assistance. I was certainly intrigued when I came across the bounty - I was unaware of this method of attack, and @martinmarinov's dissertation was fascinating.

Do let me know if you know of any similar bounties.

**Comment by mgkuhn** [comment]
https://www.bountysource.com/teams/tempestsdr

**Comment by xloem** [comment]
> [Martin's Master thesis](https://raw.githubusercontent.com/martinmarinov/TempestSDR/master/documentation/acs-dissertation.pdf) does explain parts of the the underlying theory and the algorithms used in his implementation in Chapter 3. I am in the process of writing up a more detailed tutorial on algorithms for visualizing compromising video emanations from SDR IQ data (including some newer algorithms not yet found in TempestSDR). I'll add a note here when that paper is ready.

@mgkuhn thank you so much for your maintenance work on this public repository.  Did you ever finish the tutorial and paper you mentioned here in 2017?

**Comment by xloem** [comment]
Hey, I'm so sorry, I am actually on the autism spectrum.  I'm not sure what to make of your :eyes: reply: I'm not sure what this means.

Once, in the USA, I contacted a shielded room manufacturer asking if I could purchase plans from them.  I was hoping to find a way to provide ways for communities to design and build community shielded rooms at makerspaces.

I was informed that I needed paperwork regarding access to classified information to be provided such plans.  This surprised me: I was not expecting it.

If you guys might not end up sharing your work and research with the wider community, do you know if it is safe for people to pursue research like this on their own?  Or are there laws or organisations preventing it?

**Comment by mgkuhn** [comment]
I'm not sure either what these GitHub eyes stand for, but “embarrassed look remembering that promised tutorial still hasn't appeared” would be one legitimate interpretation.

**Comment by mgkuhn** [comment]
I don't think shielded rooms are a classified technology. There are plenty of companies selling components, or offer building and/or testing them as a service. It's quite an industry, e.g. every hospital MRI machine stands in an EM-shielded room, for example. Just one example supplier: https://hollandshielding.com/Faraday-cages-standard-custom-made-EMI-shielded-test-boxes
