### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by RCCRAFT1** [martinmarinov/TempestSDR#28]
Can't this just be an exe? It would be so much easier,

**Comment by RCCRAFT1** [comment]
And it crashes, AND I am using windows so I can't/don't know how to recompile stuff.

**Comment by jeandudey** [comment]
Not my project but [here](https://github.com/martinmarinov/TempestSDR#release) is the solution, please read :).

**Comment by RCCRAFT1** [comment]
Bruh, make isn't a thing in Windows

**Comment by jeandudey** [comment]
_Bruh_, Java is a thing on all OSes.

![Screenshot from 2020-05-01 10-15-43](https://user-images.githubusercontent.com/5952531/80816230-bd906900-8b94-11ea-8351-fa0426eed1ec.png)

**Comment by RCCRAFT1** [comment]
The file doesn't open, so I have to use the "make" stuff. 
![Capture](https://user-images.githubusercontent.com/43323661/80816584-9fbb0800-8b84-11ea-8cd2-081fcd511bde.PNG)

**Comment by jeandudey** [comment]
> The file doesn't open, so I have to use the "make" stuff.
> ![Capture](https://user-images.githubusercontent.com/43323661/80816584-9fbb0800-8b84-11ea-8cd2-081fcd511bde.PNG)

You don't need make. [LMGTFY](https://lmgtfy.com/?q=how+can+i+open+jar+files&s=y) :+1:

Not sure if you're a troll but anyway if I were `make` on your computer I wouldn't execute.

**Comment by RCCRAFT1** [comment]
I meant the java file won't open when clicked and I don't know how to recompile "the project".

**Comment by RCCRAFT1** [comment]
It opens then abruptly closes

**Comment by RCCRAFT1** [comment]
And no, I'm not going to download spyware that claims to open .jar files

**Comment by jeandudey** [comment]
>And no, I'm not going to download spyware that claims to open .jar files

Java Runtime :+1:

**Comment by mgkuhn** [comment]
@jeandudey Thanks for pointing out the answer.

**Comment by RCCRAFT1** [comment]
I already have JRE, but it x86 and I don't want to reinstall java.
