### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by detona66** [martinmarinov/TempestSDR#3]
Hi, I can not compile the UHD plugin for JTempestSDR, after make all I have the message below.

~/Bureau/TempestSDR-master/TSDRPlugin_UHD$ **make all**
mkdir -p bin/LINUX/X64
mkdir -p obj
g++  -fPIC  -m64 -c src/TSDRPlugin_UHD.cpp -o obj/TSDRPlugin_UHD.o
src/TSDRPlugin_UHD.cpp:17:41: fatal error: uhd/utils/thread_priority.hpp: Aucun fichier ou dossier de ce type
compilation terminated.
makefile:151 : la recette pour la cible « obj/TSDRPlugin_UHD.o » a échouée
make: *** [obj/TSDRPlugin_UHD.o] Erreur 1

**Comment by detona66** [comment]
**I partially corrected the problem but I still have a mistake can you help me?**


TSDRPlugin_UHD$ make all
g++ -shared   -m64 -o bin/LINUX/X64/libTSDRPlugin_UHD.so obj/TSDRPlugin_UHD.o -lboost_thread -lboost_program_options -luhd
/usr/bin/ld : ne peut trouver -luhd
collect2: error: ld returned 1 exit status
makefile:146 : la recette pour la cible « bin/LINUX/X64/libTSDRPlugin_UHD.so » a échouée

**Comment by xloem** [comment]
Hi detona66,
The problem is that you have not yet installed the libuhd-dev library on your operating system.  The UHD plugin requires that you have the libuhd library already installed.  If you can't figure out how to install it, let us know what distribution of linux you have, and I would be glad to look it up for you.

**Comment by kalomix** [comment]
Hello!
Can you help me with this problem:
makefile:151: recipe for target 'obj/TSDRPlugin_UHD.o' failed
make[2]: *** [obj/TSDRPlugin_UHD.o] Error 1
make[2]: Leaving directory '/root/TempestSDR/TSDRPlugin_UHD'
cp: cannot stat '../TSDRPlugin_UHD//bin/LINUX/ARM/*.so': No such file or directory
makefile:148: recipe for target 'plugins' failed
make[1]: *** [plugins] Error 1
make[1]: Leaving directory '/root/TempestSDR/JavaGUI'
makefile:26: recipe for target 'all' failed
make: *** [all] Error 2
root@kali:~/TempestSDR# recipe for target 'obj/TSDRPlugin_UHD.o' failed
-bash: recipe: command not found


I cant install the libuhd-dev package.
thank you very much!
