### ISSUE TITLE
Do you people really do not pay attention to your issues????

### ISSUE THREAD

**Issue by RCCRAFT1** [martinmarinov/TempestSDR#31]

**Comment by mgkuhn** [comment]
“You people” are a former University of Cambridge computer-science graduate student (Martin) and his former lecturer and project supervisor (me), and this repository contains Martin's 2014 Masters dissertation project. It is released here “as is”, for anyone familiar and confident with the programming language and build tools used to play around with it. It is not a commercial product with professional support, but, depending on available time (and procrastination energy ;-) I may try my best to answer reasonable questions. Github issues are really meant for reporting bugs and contributing improvements. They are not intended as support forums, and cluttering them with chat messages will make them less useful in future as a knowledge repository for others who encounter similar problems to find what they need.

**Comment by martinmarinov** [comment]
Absolutely agree. The project is awesome and there has been some interest recently. Unfortunately there's not enough bandwidth for any of us to be able to provide continuous support here.

**Comment by mgkuhn** [comment]
@martinmarinov We probably ought to do some cleanup. I believe you as the repo owner are by default the only one who can delete issues: https://help.github.com/en/github/managing-your-work-on-github/deleting-an-issue

**Comment by martinmarinov** [comment]
@mgkuhn I see, there's no way to assign multiple owners unfortunately :(
