### ISSUE TITLE
How do you "recompile" this repo! I can't on windows!!

### ISSUE THREAD

**Issue by RCCRAFT1** [martinmarinov/TempestSDR#36]

**Comment by mgkuhn** [comment]
Hints for useful information to supply when seeking support:

* Give a description of your build environment (which OS version, which Java version)
* Which of the steps in the compile instructions in README.md did you try and where did it fail?
* What exact error message or unexpected bahavior did you get?

**Comment by RCCRAFT1** [comment]
> Hints for useful information to supply when seeking support:
> 
> * Give a description of your build environment (which OS version, which Java version)
> * Which of the steps in the compile instructions in README.md did you try and where did it fail?
> * What exact error message or unexpected bahavior did you get?

Windows 10, Latest JRE and JDK
make isn't a thing in Windows 
1. File abruptly closes when clicked, selected to open with java.exe in C:\Program Files x86\Java
2. When "make" is entered in CMD, it says: Make is not recognized as an internal or external command, program or batch file.

**Comment by mgkuhn** [comment]
README.md says: “You need to have MinGW installed.” That would include a version of GNU Make.

**Comment by RCCRAFT1** [comment]
I have the Latest MinGW installed

**Comment by mgkuhn** [comment]
The [MinGW Installation Notes](http://www.mingw.org/wiki/getting_started) say “If you ever intend to run MinGW or its applications using a cmd.exe window, you will need to make changes to your PATH environment variable. Instructions for doing so are listed in the Environment Settings section below.”

**Comment by RCCRAFT1** [comment]
In system path or this repo path?

**Comment by mgkuhn** [comment]
When in `cmd.exe` you type `path`, you get shown the value of your Windows `%PATH%` environment variable, a semicolon-separated list of folders where cmd.exe will search for an application such as “make” when you try to execute it from the command line. Make sure that the folder where your `make.exe` file from your MinGW installation resides is displayed by the `path` command, otherwise `cmd.exe` won't be able to find it. Typing “environment variable” into your Windows 10 search box might get you to the right GUI tool to configure `PATH`. (I don't have access to a Windows GUI right now to give a more detailed description of how to set PATH, but there are plenty on the web). Setting `PATH` is something you need to learn to be able to use any self-installed command-line tool on Windows.

**Comment by RCCRAFT1** [comment]
So I put MinGW on my hard drive?

**Comment by RCCRAFT1** [comment]
Sorry, I'm new to the whole java coding thing. I wish this was an exe.

**Comment by mgkuhn** [comment]
TempestSDR is actually two programs: a signal-processing component written in C, linked with the SDR API library, and a GUI front-end written in Java. Java was the GUI development environment that Martin was most comfortable with, and it was pretty portable. I recall that it worked on macOS right out of the box when we tried it for the very first time (only very minor Makefile path tweaks were needed), without Martin previously having had access to a Mac. I was quite impressed by this and therefore didn't think Java was a bad choice. We really couldn't anticipate then, back in 2013, that you would not like it seven years later ...

**Comment by RCCRAFT1** [comment]
Well, I don't use Mac.

**Comment by mgkuhn** [comment]
We couldn't anticipate that either back in 2013 ...

**Comment by RCCRAFT1** [comment]
So, any other options you might have? If you don't have anymore, I give up on this project...

**Comment by RCCRAFT1** [comment]
And, I don't think C can talk to Java...

**Comment by RCCRAFT1** [comment]
Alright, I give up.

**Comment by mgkuhn** [comment]
But Java can talk to C. (In fact most modern programming languages can call C functions, because that's what most operating system APIs are in.)
