### ISSUE TITLE
I give up trying to run this, it's too complicated for me. It wont run on windows and make dosen't work or java is cracked up and needs to be updated. ( I have latest update)

### ISSUE THREAD

**Issue by RCCRAFT1** [martinmarinov/TempestSDR#38]

**Comment by eried** [comment]
Hey @RCCRAFT1 

I wrapped it in a self-executable package:
https://github.com/eried/Research/tree/master/HackRF/TempestSDR Just double click the exe inside that zip. Includes all the dependencies.

**PS:** Chill out and close the other issues you already opened. This project is based on colaborations, there is nobody obligated to solve anyones issue and if you start spamming; you make it unpleasant for everyone.

**Comment by RCCRAFT1** [comment]
This works only with HackRF?

**Comment by eried** [comment]
Do you need another extio? It works with hackrf as extio, not sure about other boards

**Comment by RCCRAFT1** [comment]
I have an Airspy Mini and RTL-SDR.

**Comment by febs** [comment]
This geocaching fan is really missing the cooperative spirit of open source.

**Comment by xloem** [comment]
I've struggled with this project, too (although spurious issues should be closed by a maintainer in my opinion).  I was sad the maintainer wasn't interested steps toward in generalising the platform to support more kinds of work like this in one bundle.

I think a good contribution to this repo would be an alternative gui, so that java is not needed.

**Comment by mgkuhn** [comment]
This project was @martinmarinov's Master's thesis, written back in 2013/14 (which I supervised at the time). It is provided here as-is, for anyone interested to play with, but it is not an actively maintained product aimed at consumers unfamiliar with the development tools needed to compile it. I'm personally not using it any more actively; we had later projects in our group that implemented similar (and in some cases more advanced) functionality in other languages (e.g. C++ and Julia). I'll see whether I can release one of these as well later this year, where I might be able to provide more active support. (I'm not a Java developer myself.)
