### ISSUE TITLE
Compiling/Running Issue

### ISSUE THREAD

**Issue by cyb3rr0nn13** [martinmarinov/TempestSDR#41]
what do I have to do to get this compiled? 
or better still, to execute! 
I tried it in windows 10 .... does not work .... 
in Raspbian I made it, but it does not run .... because of Java ..... same for Windows, after i copied it to the fucking device.... constantly this message here

Where does it run actually? On TempleOS or what?

Best regards
![error](https://user-images.githubusercontent.com/60270666/93131875-06286900-f6d5-11ea-938b-401f8d2f8f84.png)

**Comment by eried** [comment]
Check: https://github.com/eried/Research/tree/master/HackRF/TempestSDR tell me if that one runs (the zip file)

**Comment by cyb3rr0nn13** [comment]
Affirmative :+1:
