### ISSUE TITLE
How build and use TempestSDR for ARM64 linux/MAC

### ISSUE THREAD

**Issue by CuberHuber** [martinmarinov/TempestSDR#56]

**Comment by filippt1** [comment]
Have you figured it out? I have the same problem.

**Comment by CuberHuber** [comment]
> Have you figured it out? I have the same problem.

No, I still have that problem

**Comment by filippt1** [comment]
Hello. I have found a solution that worked for me. I am using Apple Silicon and Homebrew.

First, you need to install UHD drivers and boost libraries:
```
brew install boost
brew install uhd
```

The original TSDRPlugin_UHD makefile has wrong paths for Homebrew users. After fixing the paths, you also need to add a flag for compiler to use -std=c++11 .

So, in TSDRPlugin_UHD/makefile , on:
```
line 31: GPP?=g++ -std=c++11
line 54: HOMEBREW_HOME ?= /opt/homebrew
line 116: LIBRARIES+=-L/opt/homebrew/lib -lboost_thread-mt -lboost_program_options-mt -lboost_system-mt -luhd

```
After fixing those errors, I still could not compile. I was getting:
```
src/TSDRPlugin_SDRPlay.c:21:11: fatal error: 'mirsdrapi-rsp.h' file not found
        #include <mirsdrapi-rsp.h>
```
This error was fixed [here](https://github.com/SDRplay/dump1090/issues/5) .

If you're not planning to use SDRPlay, you can just skip compiling the plugin for SDRPlay.
In JavaGUI/makefile , on:
`line 93: PLUGINS += TSDRPlugin_UHD # TSDRPlugin_SDRPlay`

After you've built the executable from JavaGUI folder, you need to open it with:
`java -jar JTempestSDR.jar`
Double-clicking the .jar file did not work for me, it crashes immediately after starting.

If you're getting TSDRLibraryNotCompatible exception, try force compilation for your architecture. For example: 
`make all ARCHNAME=X64`
