### ISSUE TITLE
How do I use this with an RTL-SDR?

### ISSUE THREAD

**Issue by flatflyfish** [martinmarinov/TempestSDR#7]
Hey, any advice on how to use TempestSDR with an RTL-SDR? I've now got it opening, but when I select the RTL-SDR ExtIO I always get the error "The ExtIO dll is not compatible with the current machine or does not exist. Please check the filename is correct and the file is a valid ExtIO dll file and try again".

The ExtIO works fine in HDSDR.

**Comment by mgkuhn** [comment]
Note that an RTL-SDR, with its maximum sampling rate of ~2.5 MHz, will only allow you to get very blurry images. You normally want to use a sampling rate much closer to the pixel-clock frequency of your target. Useful sampling rates and bandwidths for common PC video modes tend to start at about 20 MHz. (I don't have any experience with ExtIO or Windows, so can't answer your question on this device driver.)

**Comment by martinmarinov** [comment]
Hello. Unfortunately I no longer have Windows so it would be difficult for me to debug.

I would assume that one reason might be you have a 64 bit java and a 32 bit ExtIO or vice versa.

But yeah, rtl-sdrs do not generally yield good results. In the past I was only able to get some shadows that look like the screen but you will not be able to read any text.

**Comment by flatflyfish** [comment]
I got it just had to compile with x86, so thanks for that tip.

RTL's works okay, it is blurry but the overall picture is there. Fun to play with.

**Comment by martinmarinov** [comment]
Happy that helped!

**Comment by josx** [comment]
Is there any way i could use my rtl-sdr with TempestSDR?
I am using gnu/linux, it seems that TempestSDR doesnt  find the device

**Comment by RduMarais** [comment]
Same here, is there any way to make it work with Linux ? 
I see the libs are in the archive though
